const ERROR_CODES = {
  INVALID_DATA_CODE: 400,
  AUTH_ERROR_CODE: 401,
  FORBIDDEN_ERROR_CODE: 403,
  NOT_FOUND_CODE: 404,
  CONFLICT_ERROR_CODE: 409,
  DEFAULT_ERROR_CODE: 500,
};

module.exports = ERROR_CODES;
